In [1]:
import pandas as pd


df2019 = pd.read_csv("Resources/Cohort_2019.csv")
df2020 = pd.read_csv("Resources/Cohort_2020.csv")
df2021 = pd.read_csv("Resources/Cohort_2021.csv")
df2022 = pd.read_csv("Resources/Cohort_2022.csv")
df2023 = pd.read_csv("Resources/Cohort_2023.csv")

In [ ]:
df2019.head()

In [ ]:
df2021.head()

In [ ]:
df2023.head()

In [3]:
df_combined = pd.concat([df2019, df2020, df2021, df2022, df2023], ignore_index=True)
df_combined

,Cohort Year,Graduation Rate Type,LEA Entity ID,LEA Name,School Entity ID,School Name,County,Subgroup,Number Graduated,Number in Cohort,Percent Graduated in 4 Years
0,2019,4 Year,4158,Chinle Unified District,4737,Chinle High School,Apache,ELL Cohort,*,*,43.75
1,2019,4 Year,4158,Chinle Unified District,4737,Chinle High School,Apache,All,180,247,72.87
2,2019,4 Year,4158,Chinle Unified District,4737,Chinle High School,Apache,Male,78,118,66.1
3,2019,4 Year,4158,Chinle Unified District,4737,Chinle High School,Apache,Homeless Cohort,*,*,*
4,2019,4 Year,4158,Chinle Unified District,4737,Chinle High School,Apache,Female,102,129,79.07
...,...,...,...,...,...,...,...,...,...,...,...
39203,2023,4 Year,1001949,Arizona Goodwill Education Services,1001974,The Excel Center - Encanto,Maricopa,Female,*,106,*
39204,2023,4 Year,1001949,Arizona Goodwill Education Services,1001974,The Excel Center - Encanto,Maricopa,Hispanic or Latino,*,65,*
39205,2023,4 Year,1001949,Arizona Goodwill Education Services,1001974,The Excel Center - Encanto,Maricopa,Male,*,27,*
39206,2023,4 Year,1001949,Arizona Goodwill Education Services,1001974,The Excel Center - Encanto,Maricopa,Multiple Races,*,*,*
39207,2023,4 Year,1001949,Arizona Goodwill Education Services,1001974,The Excel Center - Encanto,Maricopa,White,*,32,*

In [5]:
df_combined = df_combined.set_index("Cohort Year")
df_combined.tail()

,Graduation Rate Type,LEA Entity ID,LEA Name,School Entity ID,School Name,County,Subgroup,Number Graduated,Number in Cohort,Percent Graduated in 4 Years
Cohort Year,,,,,,,,,,
2023,4 Year,1001949,Arizona Goodwill Education Services,1001974,The Excel Center - Encanto,Maricopa,Female,*,106,*
2023,4 Year,1001949,Arizona Goodwill Education Services,1001974,The Excel Center - Encanto,Maricopa,Hispanic or Latino,*,65,*
2023,4 Year,1001949,Arizona Goodwill Education Services,1001974,The Excel Center - Encanto,Maricopa,Male,*,27,*
2023,4 Year,1001949,Arizona Goodwill Education Services,1001974,The Excel Center - Encanto,Maricopa,Multiple Races,*,*,*
2023,4 Year,1001949,Arizona Goodwill Education Services,1001974,The Excel Center - Encanto,Maricopa,White,*,32,*

In [9]:
df_combined = df_combined.drop(columns=['LEA Entity ID', 'Graduation Rate Type'])
df_combined

,LEA Name,School Entity ID,School Name,County,Subgroup,Number Graduated,Number in Cohort,Percent Graduated in 4 Years
Cohort Year,,,,,,,,
2019,Chinle Unified District,4737,Chinle High School,Apache,ELL Cohort,*,*,43.75
2019,Chinle Unified District,4737,Chinle High School,Apache,All,180,247,72.87
2019,Chinle Unified District,4737,Chinle High School,Apache,Male,78,118,66.1
2019,Chinle Unified District,4737,Chinle High School,Apache,Homeless Cohort,*,*,*
2019,Chinle Unified District,4737,Chinle High School,Apache,Female,102,129,79.07
...,...,...,...,...,...,...,...,...
2023,Arizona Goodwill Education Services,1001974,The Excel Center - Encanto,Maricopa,Female,*,106,*
2023,Arizona Goodwill Education Services,1001974,The Excel Center - Encanto,Maricopa,Hispanic or Latino,*,65,*
2023,Arizona Goodwill Education Services,1001974,The Excel Center - Encanto,Maricopa,Male,*,27,*
2023,Arizona Goodwill Education Services,1001974,The Excel Center - Encanto,Maricopa,Multiple Races,*,*,*
2023,Arizona Goodwill Education Services,1001974,The Excel Center - Encanto,Maricopa,White,*,32,*

In [2]:
df_combined.to_csv('2019_2023_cohorts', index=True)

NameError: name 'df_combined' is not defined